import { test, expect } from '@playwright/test';
test('OTP login, direct execution, pause/resume, browser refresh reconnects to the same job, stop', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByText('Desktop connected', { exact: true })).toBeVisible();
  await page.getByLabel('NAS address').fill('https://nas.example.com:5001');
  await page.getByLabel('Username', { exact: true }).fill('desktop-user');
  await page.getByLabel('Password', { exact: true }).fill('secret');
  await page.getByRole('button', { name: 'Connect to NAS' }).click();
  await expect(page.getByRole('alert')).toContainText('Two-factor');
  await page.getByLabel('Password', { exact: true }).fill('secret');
  await page.getByLabel('Two-factor code required').fill('123456');
  await page.getByRole('button', { name: 'Connect to NAS' }).click();
  await expect(page.getByText('Connected as')).toBeVisible();
  await page.getByLabel('Space', { exact: true }).selectOption('both');
  await expect(page.getByRole('heading', { name: 'Library backlog' })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Choose space' })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Generate previews' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Refresh', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Execute now' })).toBeEnabled();
  await page.getByRole('button', { name: 'Execute now' }).click();
  await expect(page.getByText(/Current batch dates:/)).toBeVisible();
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeEnabled();
  const original = await page.request.get('/api/state').then(r => r.json());
  await page.getByRole('button', { name: 'Pause', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeEnabled();
  await page.reload();
  await expect(page.getByRole('button', { name: 'Resume', exact: true })).toBeEnabled();
  const reconnected = await page.request.get('/api/state').then(r => r.json());
  expect(reconnected.job.id).toBe(original.job.id);
  expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain('secret');
  await page.getByRole('button', { name: 'Resume', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Stop', exact: true }).click();
  await expect(page.getByText('stopped · Both spaces', { exact: true })).toBeVisible();
  const stopped = await page.request.get('/api/state').then(r => r.json());
  expect(stopped.job.failed).toBe(0); expect(stopped.job.cancelled).toBeGreaterThan(0);
  await page.screenshot({ path: '.test-data/interface.png', fullPage: true });
});
